

# Base Kubernetes deployment artifact.
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: "model-training-api"
    app.kubernetes.io/name: "model-training-api"
  name: "model-training-api"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: "model-training-api"
      app.kubernetes.io/name: "model-training-api"
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: "model-training-api"
        app.kubernetes.io/name: "model-training-api"
    spec:
      {{- with .Values.deployment.securityContext }}
      securityContext:
        {{- toYaml . | nindent 12}}
      {{- end }}
      serviceAccountName: "model-training-api"
      automountServiceAccountToken: {{ .Values.deployment.automountServiceAccountToken | default true }}
      {{- with .Values.deployment.volumes }}
      volumes:
        {{- toYaml . | nindent 12}}
      {{- end }}
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 12}}
      {{- end }}
      {{- with .Values.deployment.initContainers }}
      initContainers:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      containers:
        - name: "model-training-api"
          {{ if .Values.image.tag }}
          image: "{{ .Values.image.dockerRepo }}{{ .Values.image.name }}:{{ .Values.image.tag }}"
          {{ else }}
          image: "{{ .Values.image.dockerRepo }}{{ .Values.image.name }}"
          {{ end }}
          imagePullPolicy: "{{ .Values.image.imagePullPolicy }}"
          {{- with .Values.deployment.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12}}
          {{- end }}
          {{- with .Values.deployment.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{ if .Values.deployment.command }}
          command: {{ .Values.deployment.command }}
          {{ end }}
      hostname: {{ .Values.hostname }}
      restartPolicy: {{ .Values.deployment.restartPolicy }}
      {{- with .Values.deployment.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}