# Default values for model training api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

hostname: model-training-api
image:
  name: ghcr.io/boozallen/aissemble-model-training-api
  imagePullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.10.0-SNAPSHOT"

service:
  spec:
    ports:
      - name:  "5001" 
        port:  5001 
        targetPort: 80

configMap:
  trainingApiConfig: |
    project_name=test-lineage
    docker_registry=docker-registry-PLACEHOLDER/repository/
    image_prefix=
    image_tag=1.0.0-SNAPSHOT
    image_pull_policy=Always
  trainingApiConfigDev: |
    image_tag=latest
    docker_registry=
    image_pull_policy=IfNotPresent

deployment:
  ports:
    - name: http-1
      containerPort:  5001 
      protocol: TCP
  env:
    - name: KRAUSENING_BASE
      value: /opt/app/resources/config/base
  volumeMounts:
    - name: training-api-config
      mountPath: /opt/app/resources/config/base
    - name: training-api-config-dev
      mountPath: /opt/app/resources/config/extensions
  volumes:
    - name: training-api-config
      configMap:
        name: training-api-config
        items:
          - key: training-api-config.properties
            path: training-api-config.properties
    - name: training-api-config-dev
      configMap:
        name: training-api-config
        items:
          - key: training-api-config-dev.properties
            path: training-api-config.properties

  restartPolicy: Always

ingress:
  enabled: true
  metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
  hosts:
    - host: model-training-api-ai.boozallen.github.io
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: model-training-api
              port:
                number:  5001 
  status: 10.192.83.167
